name: transformer
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - astroid=2.2.5=py36_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_1
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.7.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - isort=4.3.21=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - json5=0.8.4=py_0
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - jupyterlab=1.0.2=py36hf63ae98_0
  - jupyterlab_server=1.0.0=py_0
  - kiwisolver=1.1.0=py36h0a44026_0
  - lazy-object-proxy=1.4.1=py36h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.0=py36h54f8f79_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl_fft=1.0.12=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.0=py36_0
  - numpy-base=1.16.4=py36h6575580_0
  - openssl=1.1.1c=h1de35cc_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.0=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.1.1=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.4.2=py_0
  - pylint=2.3.1=py36_0
  - pyparsing=2.4.0=py_0
  - pyrsistent=0.14.11=py36h1de35cc_0
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.0=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - rope=0.14.0=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - sqlite=3.29.0=ha441bb4_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - typed-ast=1.3.4=py36h1de35cc_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.4=py36_0
  - wrapt=1.11.2=py36h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - chardet==3.0.4
    - dill==0.3.0
    - future==0.17.1
    - gast==0.2.2
    - google-pasta==0.1.7
    - googleapis-common-protos==1.6.0
    - grpcio==1.22.0
    - h5py==2.9.0
    - idna==2.8
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - numpy==1.17.0
    - promise==2.2.1
    - protobuf==3.9.0
    - psutil==5.6.3
    - requests==2.22.0
    - six==1.12.0
    - tb-nightly==1.14.0a20190603
    - tensorflow==2.0.0b1
    - tensorflow-datasets==1.1.0
    - tensorflow-metadata==0.14.0
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019060501
    - tqdm==4.32.2
    - urllib3==1.25.3
    - werkzeug==0.15.5
prefix: /usr/local/miniconda3/envs/transformer

