name: transformer
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - astroid=2.1.0=py36_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - gast=0.2.2=py36_0
  - grpcio=1.16.1=py36h044775b_1
  - h5py=2.9.0=py36h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - intel-openmp=2019.1=144
  - isort=4.3.4=py36_0
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - lazy-object-proxy=1.3.1=py36h1de35cc_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libprotobuf=3.6.1=hd9629dc_0
  - markdown=3.0.1=py36_0
  - mccabe=0.6.1=py36_1
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.15.4=py36hacdab7b_0
  - numpy-base=1.15.4=py36h6575580_0
  - openssl=1.1.1a=h1de35cc_0
  - pip=19.0.1=py36_0
  - protobuf=3.6.1=py36h0a44026_0
  - pylint=2.2.2=py36_0
  - python=3.6.8=haf84260_0
  - readline=7.0=h1de35cc_5
  - rope=0.11.0=py36_0
  - scipy=1.2.0=py36h1410ff5_0
  - setuptools=40.7.3=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=ha441bb4_0
  - tensorboard=1.12.2=py36haf313ee_0
  - tensorflow=1.12.0=mkl_py36h2b2bbaf_0
  - tensorflow-base=1.12.0=mkl_py36h70e0e9a_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=ha441bb4_0
  - typed-ast=1.1.0=py36h1de35cc_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - wrapt=1.11.1=py36h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - yapf=0.25.0=py36_0
  - zlib=1.2.11=h1de35cc_3
prefix: /usr/local/miniconda3/envs/transformer

