name: transformer
channels:
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.0=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - astor=0.7.1=py36_0
  - astroid=2.1.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.3.2=py36_0
  - entrypoints=0.3=py36_0
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.2=py36_0
  - grpcio=1.16.1=py36h044775b_1
  - h5py=2.9.0=py36h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.3.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - isort=4.3.8=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter_client=5.2.4=py36_0
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.35.3=py36_0
  - jupyterlab_server=0.2.0=py36_0
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - lazy-object-proxy=1.3.1=py36h1de35cc_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.36=ha441bb4_0
  - libprotobuf=3.6.1=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.0.2=py36h54f8f79_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - nltk=3.4=py36_1
  - notebook=5.7.4=py36_0
  - numpy=1.16.2=py36hacdab7b_0
  - numpy-base=1.16.2=py36h6575580_0
  - openssl=1.1.1b=h1de35cc_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.4=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.0.3=py36_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.6.1=py36h0a44026_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.3.1=py36_0
  - pylint=2.2.2=py36_0
  - pyparsing=2.3.1=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2018.9=py36_0
  - pyzmq=18.0.0=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - rope=0.12.0=py36_0
  - scipy=1.2.1=py36h1410ff5_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=ha441bb4_0
  - tensorboard=1.12.2=py36haf313ee_0
  - tensorflow=1.12.0=mkl_py36h2b2bbaf_0
  - tensorflow-base=1.12.0=mkl_py36h70e0e9a_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - typed-ast=1.3.1=py36h1de35cc_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.33.1=py36_0
  - wrapt=1.11.1=py36h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - yapf=0.26.0=py36_0
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - chardet==3.0.4
    - future==0.17.1
    - googleapis-common-protos==1.5.8
    - idna==2.8
    - promise==2.2.1
    - requests==2.21.0
    - tensorflow-datasets==1.0.1
    - tensorflow-metadata==0.13.0
    - tqdm==4.31.1
    - urllib3==1.24.1
prefix: /usr/local/miniconda3/envs/transformer

